sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sharangouda/react-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true sharangouda/react-frontend npm run test
