sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sharangouda/react-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true sharangouda/react-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-frontend"
  env: "ReactFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-158213498601"
  bucket_path: "react-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
